---
- name: Create GitLab directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - "{{ gitlab_install_dir }}"
    - "{{ gitlab_install_dir }}/gitlab"
    - "{{ gitlab_install_dir }}/gitlab/config"
    - "{{ gitlab_install_dir }}/gitlab/logs"
    - "{{ gitlab_install_dir }}/gitlab/certs"

- name: Deploy GitLab environment file
  ansible.builtin.template:
    src: gitlab.env.j2
    dest: "{{ gitlab_install_dir }}/.env"
    owner: root
    group: root
    mode: "0600"
  notify: Restart GitLab

- name: Deploy GitLab Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ gitlab_install_dir }}/docker-compose.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart GitLab

- name: Start GitLab
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ gitlab_install_dir }}"
  register: gitlab_compose
  changed_when: "'Started' in gitlab_compose.stdout or 'Created' in gitlab_compose.stdout"